title: Collin Riddle
logo: https://lh3.googleusercontent.com/pw/AP1GczMzI_VmRS7kUPjVlmMPwqNqJHCyoTU6pMSGZVLI2gxlhomfaVcy3lad2uI-rmtNqocJ334J2D3IGXZj52mksoFXyo3PRteUDNRWtiSDYMt_ckZILo8=w2400
description: My Portfolio
show_downloads: true
theme: jekyll-theme-minimal
